---
version: '3.8'
services:
  grafana:
    extends:
      file: ./grafana/docker-compose.yaml
      service: grafana
  prometheus:
    extends:
      file: ./prometheus/docker-compose.yaml
      service: prometheus
  node_exporter:
    extends:
      file: ./node_exporter/docker-compose.yaml
      service: node_exporter

volumes:
  grafana-storage: {}
  prom_data: {}
